/*
 * NSE Stock List for the "Search NSE 500" combo box.
 *
 * IMPORTANT — read before relying on this in production:
 * This is a best-effort list of well-known large/mid-cap NSE-listed
 * companies compiled from general knowledge, NOT a verified live export of
 * the official NSE 500 / Nifty 500 index constituents. The real index is
 * reconstituted twice a year (March/September) by NSE Indices, and this
 * file cannot fetch that live from here. Before trusting this for anything
 * beyond exploration:
 *   1. Download the current official constituent CSV from NSE/niftyindices.com.
 *   2. Replace the NSE500_STOCKS array below with { symbol, name } entries
 *      generated from that CSV (symbol format: "NSE:<TICKER>", no ".NS"
 *      suffix — that's the Yahoo/yfinance format, not TradingView's).
 *   3. Re-test a handful of tickers against /api/live_data — TradingView's
 *      unauthenticated websocket feed used elsewhere in this app has not
 *      been verified here for NSE equities specifically (only for the
 *      index/CFD symbols already in the main dropdown), so confirm candle
 *      data actually comes back before trusting signals on any given stock.
 */

const NSE500_STOCKS = [
  { symbol: "NSE:RELIANCE", name: "Reliance Industries" },
  { symbol: "NSE:TCS", name: "Tata Consultancy Services" },
  { symbol: "NSE:HDFCBANK", name: "HDFC Bank" },
  { symbol: "NSE:ICICIBANK", name: "ICICI Bank" },
  { symbol: "NSE:INFY", name: "Infosys" },
  { symbol: "NSE:SBIN", name: "State Bank of India" },
  { symbol: "NSE:BHARTIARTL", name: "Bharti Airtel" },
  { symbol: "NSE:ITC", name: "ITC" },
  { symbol: "NSE:HINDUNILVR", name: "Hindustan Unilever" },
  { symbol: "NSE:LT", name: "Larsen & Toubro" },
  { symbol: "NSE:KOTAKBANK", name: "Kotak Mahindra Bank" },
  { symbol: "NSE:AXISBANK", name: "Axis Bank" },
  { symbol: "NSE:BAJFINANCE", name: "Bajaj Finance" },
  { symbol: "NSE:MARUTI", name: "Maruti Suzuki India" },
  { symbol: "NSE:ASIANPAINT", name: "Asian Paints" },
  { symbol: "NSE:TITAN", name: "Titan Company" },
  { symbol: "NSE:SUNPHARMA", name: "Sun Pharmaceutical" },
  { symbol: "NSE:ULTRACEMCO", name: "UltraTech Cement" },
  { symbol: "NSE:NESTLEIND", name: "Nestle India" },
  { symbol: "NSE:WIPRO", name: "Wipro" },
  { symbol: "NSE:HCLTECH", name: "HCL Technologies" },
  { symbol: "NSE:BAJAJFINSV", name: "Bajaj Finserv" },
  { symbol: "NSE:ADANIENT", name: "Adani Enterprises" },
  { symbol: "NSE:ADANIPORTS", name: "Adani Ports & SEZ" },
  { symbol: "NSE:NTPC", name: "NTPC" },
  { symbol: "NSE:POWERGRID", name: "Power Grid Corporation" },
  { symbol: "NSE:M&M", name: "Mahindra & Mahindra" },
  { symbol: "NSE:TATAMOTORS", name: "Tata Motors" },
  { symbol: "NSE:TATASTEEL", name: "Tata Steel" },
  { symbol: "NSE:JSWSTEEL", name: "JSW Steel" },
  { symbol: "NSE:HINDALCO", name: "Hindalco Industries" },
  { symbol: "NSE:COALINDIA", name: "Coal India" },
  { symbol: "NSE:ONGC", name: "Oil & Natural Gas Corp" },
  { symbol: "NSE:BPCL", name: "Bharat Petroleum" },
  { symbol: "NSE:IOC", name: "Indian Oil Corporation" },
  { symbol: "NSE:GRASIM", name: "Grasim Industries" },
  { symbol: "NSE:CIPLA", name: "Cipla" },
  { symbol: "NSE:DRREDDY", name: "Dr. Reddy's Laboratories" },
  { symbol: "NSE:DIVISLAB", name: "Divi's Laboratories" },
  { symbol: "NSE:APOLLOHOSP", name: "Apollo Hospitals" },
  { symbol: "NSE:EICHERMOT", name: "Eicher Motors" },
  { symbol: "NSE:HEROMOTOCO", name: "Hero MotoCorp" },
  { symbol: "NSE:BAJAJ-AUTO", name: "Bajaj Auto" },
  { symbol: "NSE:TVSMOTOR", name: "TVS Motor Company" },
  { symbol: "NSE:BRITANNIA", name: "Britannia Industries" },
  { symbol: "NSE:TATACONSUM", name: "Tata Consumer Products" },
  { symbol: "NSE:DABUR", name: "Dabur India" },
  { symbol: "NSE:GODREJCP", name: "Godrej Consumer Products" },
  { symbol: "NSE:MARICO", name: "Marico" },
  { symbol: "NSE:COLPAL", name: "Colgate-Palmolive India" },
  { symbol: "NSE:PIDILITIND", name: "Pidilite Industries" },
  { symbol: "NSE:SBILIFE", name: "SBI Life Insurance" },
  { symbol: "NSE:HDFCLIFE", name: "HDFC Life Insurance" },
  { symbol: "NSE:ICICIPRULI", name: "ICICI Prudential Life" },
  { symbol: "NSE:ICICIGI", name: "ICICI Lombard General Insurance" },
  { symbol: "NSE:BAJAJHLDNG", name: "Bajaj Holdings" },
  { symbol: "NSE:INDUSINDBK", name: "IndusInd Bank" },
  { symbol: "NSE:BANKBARODA", name: "Bank of Baroda" },
  { symbol: "NSE:PNB", name: "Punjab National Bank" },
  { symbol: "NSE:CANBK", name: "Canara Bank" },
  { symbol: "NSE:IDFCFIRSTB", name: "IDFC First Bank" },
  { symbol: "NSE:FEDERALBNK", name: "Federal Bank" },
  { symbol: "NSE:BANDHANBNK", name: "Bandhan Bank" },
  { symbol: "NSE:AUBANK", name: "AU Small Finance Bank" },
  { symbol: "NSE:PFC", name: "Power Finance Corporation" },
  { symbol: "NSE:RECLTD", name: "REC Limited" },
  { symbol: "NSE:LICI", name: "Life Insurance Corporation" },
  { symbol: "NSE:LTIM", name: "LTIMindtree" },
  { symbol: "NSE:TECHM", name: "Tech Mahindra" },
  { symbol: "NSE:PERSISTENT", name: "Persistent Systems" },
  { symbol: "NSE:COFORGE", name: "Coforge" },
  { symbol: "NSE:MPHASIS", name: "Mphasis" },
  { symbol: "NSE:LTTS", name: "L&T Technology Services" },
  { symbol: "NSE:OFSS", name: "Oracle Financial Services" },
  { symbol: "NSE:SIEMENS", name: "Siemens" },
  { symbol: "NSE:ABB", name: "ABB India" },
  { symbol: "NSE:HAVELLS", name: "Havells India" },
  { symbol: "NSE:BOSCHLTD", name: "Bosch" },
  { symbol: "NSE:CUMMINSIND", name: "Cummins India" },
  { symbol: "NSE:BEL", name: "Bharat Electronics" },
  { symbol: "NSE:HAL", name: "Hindustan Aeronautics" },
  { symbol: "NSE:BHEL", name: "Bharat Heavy Electricals" },
  { symbol: "NSE:SAIL", name: "Steel Authority of India" },
  { symbol: "NSE:NMDC", name: "NMDC" },
  { symbol: "NSE:VEDL", name: "Vedanta" },
  { symbol: "NSE:JINDALSTEL", name: "Jindal Steel & Power" },
  { symbol: "NSE:AMBUJACEM", name: "Ambuja Cements" },
  { symbol: "NSE:ACC", name: "ACC" },
  { symbol: "NSE:SHREECEM", name: "Shree Cement" },
  { symbol: "NSE:DALBHARAT", name: "Dalmia Bharat" },
  { symbol: "NSE:GAIL", name: "GAIL India" },
  { symbol: "NSE:PETRONET", name: "Petronet LNG" },
  { symbol: "NSE:IGL", name: "Indraprastha Gas" },
  { symbol: "NSE:ATGL", name: "Adani Total Gas" },
  { symbol: "NSE:ADANIGREEN", name: "Adani Green Energy" },
  { symbol: "NSE:ADANIPOWER", name: "Adani Power" },
  { symbol: "NSE:ADANIENSOL", name: "Adani Energy Solutions" },
  { symbol: "NSE:TATAPOWER", name: "Tata Power" },
  { symbol: "NSE:JSWENERGY", name: "JSW Energy" },
  { symbol: "NSE:NHPC", name: "NHPC" },
  { symbol: "NSE:SJVN", name: "SJVN" },
  { symbol: "NSE:IRFC", name: "Indian Railway Finance Corp" },
  { symbol: "NSE:IRCTC", name: "Indian Railway Catering & Tourism" },
  { symbol: "NSE:CONCOR", name: "Container Corporation of India" },
  { symbol: "NSE:GMRAIRPORT", name: "GMR Airports" },
  { symbol: "NSE:DLF", name: "DLF" },
  { symbol: "NSE:GODREJPROP", name: "Godrej Properties" },
  { symbol: "NSE:OBEROIRLTY", name: "Oberoi Realty" },
  { symbol: "NSE:PRESTIGE", name: "Prestige Estates Projects" },
  { symbol: "NSE:PHOENIXLTD", name: "Phoenix Mills" },
  { symbol: "NSE:LODHA", name: "Macrotech Developers (Lodha)" },
  { symbol: "NSE:INDIGO", name: "InterGlobe Aviation (IndiGo)" },
  { symbol: "NSE:TRENT", name: "Trent" },
  { symbol: "NSE:DMART", name: "Avenue Supermarts (DMart)" },
  { symbol: "NSE:ZOMATO", name: "Eternal (Zomato)" },
  { symbol: "NSE:NYKAA", name: "FSN E-Commerce (Nykaa)" },
  { symbol: "NSE:PAYTM", name: "One97 Communications (Paytm)" },
  { symbol: "NSE:POLICYBZR", name: "PB Fintech (Policybazaar)" },
  { symbol: "NSE:NAUKRI", name: "Info Edge (Naukri)" },
  { symbol: "NSE:PVRINOX", name: "PVR INOX" },
  { symbol: "NSE:JUBLFOOD", name: "Jubilant FoodWorks" },
  { symbol: "NSE:VBL", name: "Varun Beverages" },
  { symbol: "NSE:UNITDSPR", name: "United Spirits" },
  { symbol: "NSE:MCDOWELL-N", name: "United Breweries" },
  { symbol: "NSE:PGHH", name: "Procter & Gamble Hygiene" },
  { symbol: "NSE:GILLETTE", name: "Gillette India" },
  { symbol: "NSE:EMAMILTD", name: "Emami" },
  { symbol: "NSE:BATAINDIA", name: "Bata India" },
  { symbol: "NSE:PAGEIND", name: "Page Industries" },
  { symbol: "NSE:ABFRL", name: "Aditya Birla Fashion & Retail" },
  { symbol: "NSE:VOLTAS", name: "Voltas" },
  { symbol: "NSE:BLUESTARCO", name: "Blue Star" },
  { symbol: "NSE:WHIRLPOOL", name: "Whirlpool of India" },
  { symbol: "NSE:CROMPTON", name: "Crompton Greaves Consumer" },
  { symbol: "NSE:DIXON", name: "Dixon Technologies" },
  { symbol: "NSE:AMBER", name: "Amber Enterprises" },
  { symbol: "NSE:POLYCAB", name: "Polycab India" },
  { symbol: "NSE:KEI", name: "KEI Industries" },
  { symbol: "NSE:APLAPOLLO", name: "APL Apollo Tubes" },
  { symbol: "NSE:ASTRAL", name: "Astral" },
  { symbol: "NSE:SUPREMEIND", name: "Supreme Industries" },
  { symbol: "NSE:FINPIPE", name: "Finolex Industries" },
  { symbol: "NSE:CGPOWER", name: "CG Power & Industrial" },
  { symbol: "NSE:THERMAX", name: "Thermax" },
  { symbol: "NSE:AIAENG", name: "Action Construction Equipment" },
  { symbol: "NSE:SKFINDIA", name: "SKF India" },
  { symbol: "NSE:TIMKEN", name: "Timken India" },
  { symbol: "NSE:SCHAEFFLER", name: "Schaeffler India" },
  { symbol: "NSE:MOTHERSON", name: "Samvardhana Motherson" },
  { symbol: "NSE:BALKRISIND", name: "Balkrishna Industries" },
  { symbol: "NSE:MRF", name: "MRF" },
  { symbol: "NSE:CEATLTD", name: "CEAT" },
  { symbol: "NSE:APOLLOTYRE", name: "Apollo Tyres" },
  { symbol: "NSE:EXIDEIND", name: "Exide Industries" },
  { symbol: "NSE:AMARAJABAT", name: "Amara Raja Energy & Mobility" },
  { symbol: "NSE:BHARATFORG", name: "Bharat Forge" },
  { symbol: "NSE:ESCORTS", name: "Escorts Kubota" },
  { symbol: "NSE:ASHOKLEY", name: "Ashok Leyland" },
  { symbol: "NSE:SONACOMS", name: "Sona BLW Precision Forgings" },
  { symbol: "NSE:UNOMINDA", name: "UNO Minda" },
  { symbol: "NSE:LUPIN", name: "Lupin" },
  { symbol: "NSE:AUROPHARMA", name: "Aurobindo Pharma" },
  { symbol: "NSE:TORNTPHARM", name: "Torrent Pharmaceuticals" },
  { symbol: "NSE:ALKEM", name: "Alkem Laboratories" },
  { symbol: "NSE:ZYDUSLIFE", name: "Zydus Lifesciences" },
  { symbol: "NSE:GLENMARK", name: "Glenmark Pharmaceuticals" },
  { symbol: "NSE:BIOCON", name: "Biocon" },
  { symbol: "NSE:LAURUSLABS", name: "Laurus Labs" },
  { symbol: "NSE:GLAND", name: "Gland Pharma" },
  { symbol: "NSE:IPCALAB", name: "IPCA Laboratories" },
  { symbol: "NSE:ABBOTINDIA", name: "Abbott India" },
  { symbol: "NSE:PFIZER", name: "Pfizer" },
  { symbol: "NSE:SANOFI", name: "Sanofi India" },
  { symbol: "NSE:MANKIND", name: "Mankind Pharma" },
  { symbol: "NSE:METROPOLIS", name: "Metropolis Healthcare" },
  { symbol: "NSE:LALPATHLAB", name: "Dr. Lal PathLabs" },
  { symbol: "NSE:MAXHEALTH", name: "Max Healthcare Institute" },
  { symbol: "NSE:FORTIS", name: "Fortis Healthcare" },
  { symbol: "NSE:SYNGENE", name: "Syngene International" },
  { symbol: "NSE:PIIND", name: "PI Industries" },
  { symbol: "NSE:UPL", name: "UPL" },
  { symbol: "NSE:SRF", name: "SRF" },
  { symbol: "NSE:DEEPAKNTR", name: "Deepak Nitrite" },
  { symbol: "NSE:AARTIIND", name: "Aarti Industries" },
  { symbol: "NSE:NAVINFLUOR", name: "Navin Fluorine International" },
  { symbol: "NSE:TATACHEM", name: "Tata Chemicals" },
  { symbol: "NSE:GNFC", name: "Gujarat Narmada Valley Fertilizers" },
  { symbol: "NSE:CHAMBLFERT", name: "Chambal Fertilisers" },
  { symbol: "NSE:COROMANDEL", name: "Coromandel International" },
  { symbol: "NSE:BERGEPAINT", name: "Berger Paints" },
  { symbol: "NSE:KANSAINER", name: "Kansai Nerolac Paints" },
  { symbol: "NSE:AKZOINDIA", name: "Akzo Nobel India" },
  { symbol: "NSE:JKCEMENT", name: "JK Cement" },
  { symbol: "NSE:RAMCOCEM", name: "The Ramco Cements" },
  { symbol: "NSE:HEIDELBERG", name: "HeidelbergCement India" },
  { symbol: "NSE:INDIACEM", name: "The India Cements" },
  { symbol: "NSE:CENTURYPLY", name: "Century Plyboards" },
  { symbol: "NSE:GREENPANEL", name: "Greenpanel Industries" },
  { symbol: "NSE:KAJARIACER", name: "Kajaria Ceramics" },
  { symbol: "NSE:CERA", name: "Cera Sanitaryware" },
  { symbol: "NSE:HINDPETRO", name: "Hindustan Petroleum" },
  { symbol: "NSE:MRPL", name: "Mangalore Refinery & Petrochemicals" },
  { symbol: "NSE:CASTROLIND", name: "Castrol India" },
  { symbol: "NSE:GUJGASLTD", name: "Gujarat Gas" },
  { symbol: "NSE:MGL", name: "Mahanagar Gas" },
  { symbol: "NSE:OIL", name: "Oil India" },
  { symbol: "NSE:HINDCOPPER", name: "Hindustan Copper" },
  { symbol: "NSE:NALCO", name: "National Aluminium Company" },
  { symbol: "NSE:RATNAMANI", name: "Ratnamani Metals & Tubes" },
  { symbol: "NSE:WELCORP", name: "Welspun Corp" },
  { symbol: "NSE:JSPL", name: "Jindal Steel & Power" },
  { symbol: "NSE:JSL", name: "Jindal Stainless" },
  { symbol: "NSE:APLLTD", name: "Alembic Pharmaceuticals" },
  { symbol: "NSE:GESHIP", name: "Great Eastern Shipping" },
  { symbol: "NSE:SCI", name: "Shipping Corporation of India" },
  { symbol: "NSE:CONCORDBIO", name: "Concord Biotech" },
  { symbol: "NSE:LTF", name: "L&T Finance" },
  { symbol: "NSE:CHOLAFIN", name: "Cholamandalam Investment & Finance" },
  { symbol: "NSE:SHRIRAMFIN", name: "Shriram Finance" },
  { symbol: "NSE:MUTHOOTFIN", name: "Muthoot Finance" },
  { symbol: "NSE:MANAPPURAM", name: "Manappuram Finance" },
  { symbol: "NSE:PEL", name: "Piramal Enterprises" },
  { symbol: "NSE:SUNDARMFIN", name: "Sundaram Finance" },
  { symbol: "NSE:PNBHOUSING", name: "PNB Housing Finance" },
  { symbol: "NSE:LICHSGFIN", name: "LIC Housing Finance" },
  { symbol: "NSE:CANFINHOME", name: "Can Fin Homes" },
  { symbol: "NSE:BAJAJHFL", name: "Bajaj Housing Finance" },
  { symbol: "NSE:JIOFIN", name: "Jio Financial Services" },
  { symbol: "NSE:ANGELONE", name: "Angel One" },
  { symbol: "NSE:CDSL", name: "Central Depository Services" },
  { symbol: "NSE:BSE", name: "BSE Limited" },
  { symbol: "NSE:MCX", name: "Multi Commodity Exchange" },
  { symbol: "NSE:IEX", name: "Indian Energy Exchange" },
  { symbol: "NSE:CAMS", name: "Computer Age Management Services" },
  { symbol: "NSE:NUVAMA", name: "Nuvama Wealth Management" },
  { symbol: "NSE:IIFL", name: "IIFL Finance" },
  { symbol: "NSE:M&MFIN", name: "Mahindra & Mahindra Financial" },
  { symbol: "NSE:ABCAPITAL", name: "Aditya Birla Capital" },
  { symbol: "NSE:HDFCAMC", name: "HDFC Asset Management" },
  { symbol: "NSE:NAM-INDIA", name: "Nippon Life India Asset Mgmt" },
  { symbol: "NSE:UTIAMC", name: "UTI Asset Management" },
  { symbol: "NSE:STARHEALTH", name: "Star Health Insurance" },
  { symbol: "NSE:GICRE", name: "General Insurance Corporation" },
  { symbol: "NSE:NIACL", name: "New India Assurance" },
  { symbol: "NSE:YESBANK", name: "Yes Bank" },
  { symbol: "NSE:RBLBANK", name: "RBL Bank" },
  { symbol: "NSE:SOUTHBANK", name: "South Indian Bank" },
  { symbol: "NSE:UCOBANK", name: "UCO Bank" },
  { symbol: "NSE:IOB", name: "Indian Overseas Bank" },
  { symbol: "NSE:CENTRALBK", name: "Central Bank of India" },
  { symbol: "NSE:MAHABANK", name: "Bank of Maharashtra" },
  { symbol: "NSE:UNIONBANK", name: "Union Bank of India" },
  { symbol: "NSE:INDIANB", name: "Indian Bank" },
  { symbol: "NSE:J&KBANK", name: "Jammu & Kashmir Bank" },
  { symbol: "NSE:KARURVYSYA", name: "Karur Vysya Bank" },
  { symbol: "NSE:CUB", name: "City Union Bank" },
  { symbol: "NSE:DCBBANK", name: "DCB Bank" },
  { symbol: "NSE:EQUITASBNK", name: "Equitas Small Finance Bank" },
  { symbol: "NSE:UJJIVANSFB", name: "Ujjivan Small Finance Bank" },
  { symbol: "NSE:SURYODAY", name: "Suryoday Small Finance Bank" },
  { symbol: "NSE:KPITTECH", name: "KPIT Technologies" },
  { symbol: "NSE:TATAELXSI", name: "Tata Elxsi" },
  { symbol: "NSE:CYIENT", name: "Cyient" },
  { symbol: "NSE:ZENSARTECH", name: "Zensar Technologies" },
  { symbol: "NSE:BSOFT", name: "Birlasoft" },
  { symbol: "NSE:HAPPSTMNDS", name: "Happiest Minds Technologies" },
  { symbol: "NSE:ROUTE", name: "Route Mobile" },
  { symbol: "NSE:NEWGEN", name: "Newgen Software Technologies" },
  { symbol: "NSE:INTELLECT", name: "Intellect Design Arena" },
  { symbol: "NSE:SONATSOFTW", name: "Sonata Software" },
  { symbol: "NSE:MASTEK", name: "Mastek" },
  { symbol: "NSE:LATENTVIEW", name: "Latent View Analytics" },
  { symbol: "NSE:TANLA", name: "Tanla Platforms" },
  { symbol: "NSE:AFFLE", name: "Affle India" },
  { symbol: "NSE:INDIAMART", name: "IndiaMART InterMESH" },
  { symbol: "NSE:JUSTDIAL", name: "Just Dial" },
  { symbol: "NSE:RATEGAIN", name: "RateGain Travel Technologies" },
  { symbol: "NSE:MAPMYINDIA", name: "C.E. Info Systems (MapmyIndia)" },
  { symbol: "NSE:DELHIVERY", name: "Delhivery" },
  { symbol: "NSE:BLUEDART", name: "Blue Dart Express" },
  { symbol: "NSE:VRLLOG", name: "VRL Logistics" },
  { symbol: "NSE:TCI", name: "Transport Corporation of India" },
  { symbol: "NSE:GESCO", name: "Godrej Industries" },
  { symbol: "NSE:RAJESHEXPO", name: "Rajesh Exports" },
  { symbol: "NSE:TITAGARH", name: "Titagarh Rail Systems" },
  { symbol: "NSE:RVNL", name: "Rail Vikas Nigam" },
  { symbol: "NSE:RAILTEL", name: "RailTel Corporation" },
  { symbol: "NSE:IRB", name: "IRB Infrastructure Developers" },
  { symbol: "NSE:GMRINFRA", name: "GMR Infrastructure" },
  { symbol: "NSE:NBCC", name: "NBCC (India)" },
  { symbol: "NSE:NCC", name: "NCC Limited" },
  { symbol: "NSE:KNRCON", name: "KNR Constructions" },
  { symbol: "NSE:PNCINFRA", name: "PNC Infratech" },
  { symbol: "NSE:HGINFRA", name: "H.G. Infra Engineering" },
  { symbol: "NSE:KEC", name: "KEC International" },
  { symbol: "NSE:KALPATPOWR", name: "Kalpataru Projects International" },
  { symbol: "NSE:SUZLON", name: "Suzlon Energy" },
  { symbol: "NSE:INOXWIND", name: "Inox Wind" },
  { symbol: "NSE:WAAREEENER", name: "Waaree Energies" },
  { symbol: "NSE:PREMIERENE", name: "Premier Energies" },
  { symbol: "NSE:GVT&D", name: "GE Vernova T&D India" },
  { symbol: "NSE:HITACHIENE", name: "Hitachi Energy India" },
  { symbol: "NSE:TRITURBINE", name: "Triveni Turbine" }
];
